In [1]:
from ultralytics import YOLO
import cv2
import torch

In [2]:
model = YOLO(r"best.pt")

In [3]:
device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')
device

device(type='cuda', index=0)

In [4]:
video = cv2.VideoCapture(0)

width = int(video.get(cv2.CAP_PROP_FRAME_WIDTH))
height = int(video.get(cv2.CAP_PROP_FRAME_HEIGHT))

while True:
    
    ret, frame = video.read()
    
    frame = cv2.resize(frame,(width,height),interpolation = cv2.INTER_AREA)
        
    results = model.predict(frame, conf=0.7, stream = True,device = device)
    
    for result in results:
        boxes = result.boxes.cpu().numpy()  
        for box in boxes:
            r = box.xyxy[0].astype(int)
            print(r)
            cv2.rectangle(frame, r[:2], r[2:], (255, 255, 255), 2)

    cv2.imshow("input", frame)

    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
        
video.release()
cv2.destroyAllWindows()        


0: 480x640 1 face, 60.0ms
Speed: 3.0ms preprocess, 60.0ms inference, 7.0ms postprocess per image at shape (1, 3, 640, 640)

0: 480x640 1 face, 37.0ms
Speed: 4.0ms preprocess, 37.0ms inference, 4.0ms postprocess per image at shape (1, 3, 640, 640)

0: 480x640 1 face, 37.0ms
Speed: 2.0ms preprocess, 37.0ms inference, 4.0ms postprocess per image at shape (1, 3, 640, 640)



[264 310 423 480]
[261 311 419 480]
[262 311 419 480]


0: 480x640 1 face, 35.0ms
Speed: 3.0ms preprocess, 35.0ms inference, 4.0ms postprocess per image at shape (1, 3, 640, 640)

0: 480x640 1 face, 28.0ms
Speed: 3.0ms preprocess, 28.0ms inference, 3.0ms postprocess per image at shape (1, 3, 640, 640)

0: 480x640 1 face, 28.0ms
Speed: 2.0ms preprocess, 28.0ms inference, 2.0ms postprocess per image at shape (1, 3, 640, 640)

0: 480x640 1 face, 28.0ms
Speed: 2.0ms preprocess, 28.0ms inference, 2.0ms postprocess per image at shape (1, 3, 640, 640)



[260 311 421 480]
[259 312 420 480]
[261 313 419 480]
[260 313 419 480]


0: 480x640 1 face, 28.0ms
Speed: 1.9ms preprocess, 28.0ms inference, 3.0ms postprocess per image at shape (1, 3, 640, 640)

0: 480x640 1 face, 28.0ms
Speed: 3.0ms preprocess, 28.0ms inference, 2.0ms postprocess per image at shape (1, 3, 640, 640)

0: 480x640 1 face, 27.5ms
Speed: 6.0ms preprocess, 27.5ms inference, 3.0ms postprocess per image at shape (1, 3, 640, 640)

0: 480x640 1 face, 25.0ms
Speed: 3.0ms preprocess, 25.0ms inference, 2.0ms postprocess per image at shape (1, 3, 640, 640)

0: 480x640 1 face, 26.0ms


[261 312 419 480]
[260 313 420 480]
[260 313 420 480]
[260 314 419 480]
[262 313 419 480]


Speed: 2.0ms preprocess, 26.0ms inference, 2.0ms postprocess per image at shape (1, 3, 640, 640)

0: 480x640 1 face, 29.0ms
Speed: 2.0ms preprocess, 29.0ms inference, 2.0ms postprocess per image at shape (1, 3, 640, 640)

0: 480x640 1 face, 26.0ms
Speed: 2.0ms preprocess, 26.0ms inference, 2.0ms postprocess per image at shape (1, 3, 640, 640)

0: 480x640 1 face, 27.0ms
Speed: 2.0ms preprocess, 27.0ms inference, 3.0ms postprocess per image at shape (1, 3, 640, 640)

0: 480x640 1 face, 25.0ms
Speed: 2.0ms preprocess, 25.0ms inference, 3.0ms postprocess per image at shape (1, 3, 640, 640)

0: 480x640 1 face, 28.0ms


[260 315 419 479]
[261 315 419 479]
[261 315 418 480]
[261 315 419 479]
[261 315 419 480]


Speed: 2.0ms preprocess, 28.0ms inference, 3.0ms postprocess per image at shape (1, 3, 640, 640)

0: 480x640 1 face, 26.0ms
Speed: 1.0ms preprocess, 26.0ms inference, 2.0ms postprocess per image at shape (1, 3, 640, 640)

0: 480x640 1 face, 29.0ms
Speed: 2.0ms preprocess, 29.0ms inference, 3.0ms postprocess per image at shape (1, 3, 640, 640)

0: 480x640 1 face, 25.0ms
Speed: 2.0ms preprocess, 25.0ms inference, 3.0ms postprocess per image at shape (1, 3, 640, 640)

0: 480x640 1 face, 26.0ms
Speed: 2.0ms preprocess, 26.0ms inference, 3.0ms postprocess per image at shape (1, 3, 640, 640)

0: 480x640 1 face, 26.0ms


[262 314 420 480]
[262 315 420 480]
[262 317 420 480]
[262 317 420 479]
[262 317 419 480]


Speed: 3.0ms preprocess, 26.0ms inference, 4.0ms postprocess per image at shape (1, 3, 640, 640)

0: 480x640 1 face, 26.0ms
Speed: 1.0ms preprocess, 26.0ms inference, 2.0ms postprocess per image at shape (1, 3, 640, 640)

0: 480x640 1 face, 26.0ms
Speed: 3.0ms preprocess, 26.0ms inference, 3.0ms postprocess per image at shape (1, 3, 640, 640)

0: 480x640 1 face, 27.8ms
Speed: 1.0ms preprocess, 27.8ms inference, 2.0ms postprocess per image at shape (1, 3, 640, 640)

0: 480x640 1 face, 26.0ms
Speed: 3.0ms preprocess, 26.0ms inference, 2.0ms postprocess per image at shape (1, 3, 640, 640)

0: 480x640 1 face, 26.0ms


[262 316 421 479]
[263 317 421 479]
[263 317 421 479]
[263 317 421 479]
[263 316 421 480]


Speed: 1.0ms preprocess, 26.0ms inference, 2.0ms postprocess per image at shape (1, 3, 640, 640)

0: 480x640 1 face, 27.0ms
Speed: 1.0ms preprocess, 27.0ms inference, 2.0ms postprocess per image at shape (1, 3, 640, 640)

0: 480x640 1 face, 27.0ms
Speed: 3.0ms preprocess, 27.0ms inference, 3.0ms postprocess per image at shape (1, 3, 640, 640)

0: 480x640 1 face, 26.0ms
Speed: 3.0ms preprocess, 26.0ms inference, 2.0ms postprocess per image at shape (1, 3, 640, 640)

0: 480x640 1 face, 25.0ms
Speed: 1.0ms preprocess, 25.0ms inference, 3.0ms postprocess per image at shape (1, 3, 640, 640)

0: 480x640 1 face, 25.0ms


[264 317 422 480]
[263 318 421 480]
[264 316 422 479]
[264 317 422 479]
[265 314 424 480]


Speed: 2.0ms preprocess, 25.0ms inference, 2.0ms postprocess per image at shape (1, 3, 640, 640)

0: 480x640 1 face, 30.0ms
Speed: 1.0ms preprocess, 30.0ms inference, 3.0ms postprocess per image at shape (1, 3, 640, 640)

0: 480x640 1 face, 26.0ms
Speed: 4.0ms preprocess, 26.0ms inference, 3.0ms postprocess per image at shape (1, 3, 640, 640)

0: 480x640 1 face, 26.0ms
Speed: 4.0ms preprocess, 26.0ms inference, 3.0ms postprocess per image at shape (1, 3, 640, 640)

0: 480x640 1 face, 26.0ms
Speed: 3.0ms preprocess, 26.0ms inference, 2.0ms postprocess per image at shape (1, 3, 640, 640)



[268 315 426 480]
[268 314 427 480]
[267 314 427 480]
[268 315 426 480]


0: 480x640 1 face, 26.0ms
Speed: 2.0ms preprocess, 26.0ms inference, 2.0ms postprocess per image at shape (1, 3, 640, 640)

0: 480x640 1 face, 26.0ms
Speed: 4.9ms preprocess, 26.0ms inference, 2.0ms postprocess per image at shape (1, 3, 640, 640)

0: 480x640 1 face, 27.1ms
Speed: 3.0ms preprocess, 27.1ms inference, 3.0ms postprocess per image at shape (1, 3, 640, 640)

0: 480x640 1 face, 27.0ms
Speed: 1.0ms preprocess, 27.0ms inference, 2.0ms postprocess per image at shape (1, 3, 640, 640)



[268 314 427 480]
[266 316 426 480]
[266 313 425 480]
[266 313 425 480]


0: 480x640 1 face, 27.0ms
Speed: 2.0ms preprocess, 27.0ms inference, 2.0ms postprocess per image at shape (1, 3, 640, 640)

0: 480x640 1 face, 26.0ms
Speed: 2.0ms preprocess, 26.0ms inference, 2.0ms postprocess per image at shape (1, 3, 640, 640)

0: 480x640 1 face, 26.0ms
Speed: 3.0ms preprocess, 26.0ms inference, 3.0ms postprocess per image at shape (1, 3, 640, 640)

0: 480x640 1 face, 28.0ms
Speed: 1.0ms preprocess, 28.0ms inference, 2.0ms postprocess per image at shape (1, 3, 640, 640)


[267 315 426 480]
[266 313 426 480]
[267 314 425 480]
[266 314 426 480]
